apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: k8s-demo-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: port
        - name: API_VERSION
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: api-version
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: environment
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: db-connection-string
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: api-key
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: secrets-volume
          mountPath: /app/secrets
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: backend-config-files
      - name: secrets-volume
        secret:
          secretName: backend-secret-files
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
  type: NodePort
